scope: knb-lter-cap
identifier: 736
baseURL: https://storage.googleapis.com/asuke-aws-gios-data/datasets/cap/
project: lter
title: 'Hourly Mean Radiant Temperature and Shade Raster Dataset for Three PASS (Phoenix Area Social Survey) Neighborhoods, Arizona, USA (2025)'
maintenance: none
geographic_description: 'CAP LTER study area: greater Phoenix, Arizona (USA) metropolitan area and surrounding Sonoran desert region'
runtime:
  raster_root: /scratch/srearl/tiffs
  entities_output_dir: /scratch/srearl/out_735/
  max_rasters: null
  epsg: 3857
  coverage_begin: '2025-05-01'
  coverage_end: '2025-09-30'
